### ISSUE TITLE
Add automated test for Epinio UI

### ISSUE THREAD

**Issue by ldevulder** [epinio/epinio#1000]
We have to find a way to do automated tests on the Epinio UI.

There is multiple ways to do this:
- only the API (like other Rancher products)
- as a real user (with something like Selenium)
- both

Let's discuss the pros and cons of all and anyone can add his ideas here also ;-)

**Comment by kkaempf** [comment]
Rancher Dashboard is based on [Vue](https://vuejs.org) and Vue recommends [several e2e test frameworks](https://v3.vuejs.org/guide/testing.html#recommendations-2).
And apparently UI developers [have already](https://github.com/rancher/dashboard/blob/a5b9683884b608f6d8d0f9d2b5400c35e43c2993/package.json#L125) selected [Cypress](https://www.cypress.io). :wink:

**Comment by juadk** [comment]
Yes, yesterday we talked about Cypress with @prabalsharma  and we definitely want to give it a try.
Thanks @catherineluse for the info.

**Comment by prabalsharma** [comment]
- [ ] https://github.com/epinio/epinio/issues/1031
- [ ] https://github.com/epinio/epinio/issues/1032
- [ ] https://github.com/epinio/epinio/issues/1033
- [ ] https://github.com/epinio/epinio/issues/1034
- [ ] https://github.com/epinio/epinio/issues/1035
- [ ] https://github.com/epinio/epinio/issues/1036

**Comment by juadk** [comment]
Good progress last week, we are close to the end of the first version I think (improvements will be needed):
![Cypress_ok](https://user-images.githubusercontent.com/6025636/148733515-322ff9d1-451a-489d-95ac-0af0493d219e.png)
We are now more familiar Cypress so coding new scenarios is faster.

**Comment by juadk** [comment]
I think we can close this epic, [upgrade](https://github.com/epinio/epinio-end-to-end-tests/issues/4) and [CI](https://github.com/epinio/epinio-end-to-end-tests/issues/55) will be done in there own cards.
