### ISSUE TITLE
Multiple app helm charts

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1270]
**Is your feature request related to a problem? Please describe.**
An operator might want to allow developers to pick from a few different flavors of application to build. 

**Describe the solution you'd like**

We should allow:
- Operators to add/remove charts
- Operators to set default chart
- Developers to list charts
- Developers to specify target chart on push

Charts should also have descriptions or labels that we can show in the list.

**Describe alternatives you've considered**
You could use multiple epinio installs but the overhead is too large to be realistic 

### TODO

- [x] Extend AppCRD to hold chart (URL!) used to deploy app. -- https://github.com/epinio/application/pull/7
- [x] Define CRD for holding chart references (name, url, description, k8s labels for recognition)
- [x] Create CR for the above CRD, to reference the standard chart. -- https://github.com/epinio/helm-charts/pull/167
- [x] Going for local default initially ~~Define and create ConfigMap to hold the global information about default chart, set to standard. (Check if we already have a config map for global epinio state) -- :construction: Only if we wish to support a global default.~~
- [x] Provide app chart CR name from client. ~~Change app deployment to read default from global map~~.
- [x] Extend API app push endpoint to save to app CR. -- https://github.com/epinio/epinio/pull/1340
- [x] Read chart repo/url and use for deployment.
- [x] Rewrite app export to take app chart information saved in app CR.
- [x] Implement API endpoint and cli command to list app chart CRs.
- [x] Tests for above
- [x] Implement API endpoint and cli command to create app chart CRs.
- [x] Tests for above
- [x] Implement API endpoint and cli command to delete app chart CRs.
- [x] Tests for above
- [x] Implement cli command to change default app chart (local config).
- [x] Tests for above
- [x] Extend `app push` to set app chart by name
- [x] Tests for above
- [x] Extend `app create` to set app chart by name
- [x] Extend API app create endpoint to save app chart name
- [x] Tests for above
- [x] Extend `app update` to change named app chart (undeployed app only)
- [x] Tests for above
- [x] Extend `app manifest` to export app chart name
- [x] Tests for above
- [x] Extend `app show` to display app chart name.
- [x] Modify server app fetch to provide app chart
- [x] Tests for above
- [x] Extend swagger defs in `internal/api/v1/docs/`, regenerate swagger json.
- [x] Fix `app export` for app chart specified by name+helmrepo.

Note: Saving the chart url instead of a name means that (re)deployment still has a chance of using the chart even if the name for it is removed (the ConfigMap). Fail only if the chart itself is not accessible anymore.

**Comment by manno** [comment]
* Endpoints to create/update/list/delete meta info about helm charts (and their URLs)
* deploy apps with a specific chart

**Comment by jimmykarily** [comment]
Deployed apps should store the used chart somewhere on the AppCRD. What happens when someone deletes that chart? The applications can still run but if someone tries to push again, Epinio won't have access to the previously used chart. Maybe we should require an explicit chart then?
