### ISSUE TITLE
Service CRUD

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1332]
Follow up of: https://github.com/epinio/epinio/issues/1281

We now have a catalog of services. We need endpoints and command to create, delete, list, show service instances.

## Acceptance Criteria

- [x] There is an `epinio service create` command that creates services from the catalog
- [x] There is an `epinio service show` command that displays detailed information about a service instance (e.g. the service it belongs to, whether it's ready/deployed or not, etc)
- [x] There is an `epinio service bind` command that binds the service's secrets to an application and annotates them to makes them epinio "Configurations"
- [x] No relics are left behind. The custom resource `helmchart` should be deleted when a service instance is deleted. The same should happen when a namespace is deleted with `epinio namespace delete`. - #1350 

- [x] There is an `epinio service delete` command that deletes provisioned services - #1354 
- [x] There is an `epinio service list` command that shows a list of all service instances (in the currently targeted namespace). The catalog service they belong to is also visible. - #1349 

## Notes

- No `update` endpoint yet. For now we won't implement "user defined values" for helm charts. If the operator wants to allow different set of values, they will have to create a different catalog service.

**Comment by enrichman** [comment]
Automatically closed.

Reopen for the missing bullet points.
