### ISSUE TITLE
[Epic] Allow to override default port

### ISSUE THREAD

**Issue by olblak** [epinio/epinio#1792]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/epinio/epinio/issues/1791
I would like to be able to override default application port quickly

**Describe the solution you'd like**
I would like to be able to run `epinio push --name myapplication --port 1313`

**Describe alternatives you've considered**
We discussed the possibility to do that via custom helm Chart but we found it a bit heavy for this kind of setting

**Additional context**

---

Updates (@enrichman): https://github.com/epinio/epinio/issues/1792#issuecomment-1438034128  

---

## Tasks
- [x] https://github.com/epinio/helm-charts/pull/391
- [x] https://github.com/epinio/ui/issues/140
- [x] https://github.com/epinio/epinio/issues/2126

**Comment by agracey** [comment]
I think this can be done more easily by templating the service yaml based on a value to be overwritten using 

`epinio app push -n <some name> -v port 1313`

**Comment by agracey** [comment]
I think there might be several places like this where our default app template could be extended like this without needing to expose it with it's own flag.

**Comment by enrichman** [comment]
I agree on extending our default template. So in order to complete this we will need to:

- [ ] update the [application chart](https://github.com/epinio/helm-charts/tree/main/chart/application), and use the new one as [default](https://github.com/epinio/helm-charts/blob/epinio-application-0.1.24/chart/epinio/templates/default-app-chart.yaml#L15) 

this should be enough since the `-v/--chart-value` flag is already covered, but we need also to

- [ ] add the values to the UI
- [ ] tests for app upgrades from the old app chart to the new one (not sure if we have these)
- [ ] tests for the UI
- [ ] update documentation accordingly
