### ISSUE TITLE
[Epic] Add port forward for services

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2037]
**Describe the solution you'd like**
It would be nice to connect to a running service with the port forwarding.

I.e.: connect to a mongoDB with a client, running an `epinio service port-forward mydb 27017`
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/epinio/issues/2365
- [ ] https://github.com/epinio/epinio/pull/2366
- [ ] https://github.com/epinio/epinio/pull/2361
- [ ] https://github.com/epinio/epinio/pull/2390
```

**Comment by gitricko** [comment]
+1

**Comment by enrichman** [comment]
Small bug to fix in the next relase: https://github.com/epinio/epinio/issues/2425
