### ISSUE TITLE
PCCI Enhance RKE2 EC2 workflow

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#2203]
Follow up issue for https://github.com/epinio/epinio/issues/2122

Current workflow https://github.com/epinio/epinio/blob/main/.github/workflows/rke2-lh-ec2.yml does:
- Details about preparation an instance template & co. under AWS described in the original issue
- Install dependencies like awscli on runner
- Provision EC2 instance(s) - multinode supported here
- Deploy RKE2 over SSH - without multinode support so far - part for installing RKE2 agents not implemented yet
- Deploy Longhorn v1.4.1 as default SC
- Install Acceptance4 from EKS - deploys nginx-ingress and configures route53 CNAME entries
- Delete EC2 instances

```[tasklist]
### Tasks
- [ ] Add multinode support - currenly only single node RKE2 server
- [ ] Add inputs for specific RKE2 and Longhorn version
- [ ] Implement external registries
- [ ] Move the code from yml to Makefile if possible
- [ ] Unify `Install Dependencies` and `Install Tools` steps
```
