### ISSUE TITLE
Controller refactoring and cleanup

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2234]
In our code there are 6 "controllers" for our APIs:

- https://github.com/epinio/epinio/blob/main/internal/api/v1/appchart/controller.go
- https://github.com/epinio/epinio/blob/main/internal/api/v1/configuration/controller.go
- https://github.com/epinio/epinio/blob/main/internal/api/v1/env/controller.go
- https://github.com/epinio/epinio/blob/main/internal/api/v1/configurationbinding/controller.go
- https://github.com/epinio/epinio/blob/main/internal/api/v1/namespace/controller.go
- https://github.com/epinio/epinio/blob/main/internal/api/v1/service/controller.go

They have no internal state, and they are not really used. They are created just to access their functions in the API router.

Example: https://github.com/epinio/epinio/blob/main/internal/api/v1/router.go#L116
```
errorHandler(env.Controller{}.Match)
```

This could be simplified dropping the controller and calling the func directly, as I tried with the `application.Controller` [here](https://github.com/epinio/epinio/pull/2190).

```[tasklist]
### Tasks
- [ ] https://github.com/epinio/epinio/issues/2247
- [ ] https://github.com/epinio/epinio/issues/2254
- [ ] https://github.com/epinio/epinio/issues/2273
- [ ] https://github.com/epinio/epinio/issues/2281
- [ ] https://github.com/epinio/epinio/issues/2276
- [ ] https://github.com/epinio/epinio/issues/2283
```
