### ISSUE TITLE
Support deploying application from private & enteprise github/gitlab

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#2236]
**Is your feature request related to a problem? Please describe.**
Currently users can supply a reference to a public git location as a source for an application. This can be public github or gitlab. Any git location that requires credentials though is not supported. This extends to github and gitlab private (hosted by them) or enterprise (hosted elsewhere). 

> This issue is purely about github / gitlab and not any git that requires credentials. We should bear in mind that this could be supported in future.

**Describe the solution you'd like**
- Users are able to manage github / gitlab api keys in epinio
  - create / list / edit / delete api keys 
- The api keys will be associated with either a public or enterprise github / gitlab instance
  - If the instance if for enterprise they will need to supply the url
- The api key will be used
  - by the backend to fetch source for an application
  - by the UI to show git information (repos, branches, commits, etc). These requests will require the api key. A proxy from ui to backend (where the key is added) to git might be best
- For enterprise github / gitlab a url will also need to be stored

**Describe alternatives you've considered**
- The ui has a lot of this mechanism in place already (persisting credentials, proxying requests, etc). We could go down this approach, but..
  - the cli would not be able to use the feature
  - ui would need to fetch source then supply it as a appl deployment type 'folder', which isn't great for redeploy world

---

From @enrichman 

Adding the tasklist with the issues that we have found after the meeting

```[tasklist]
### Tasks
- [ ] https://github.com/epinio/epinio/issues/2488
- [ ] https://github.com/epinio/epinio/pull/2503
- [ ] https://github.com/epinio/epinio/issues/2489
```

**Comment by yodatak** [comment]
annother way is to permit to have somethink like this  git clone https://gitlab-ci-token:<private token>@git.example.com/myuser/myrepo.git

**Comment by richard-cox** [comment]
@enrichman I've created https://github.com/epinio/ui/issues/327 for the UI side (i'm still fleshing out some of the task)

**Comment by enrichman** [comment]
We should have a quick look/test on the UI side for private repo deployed via CLI (or even UI) when updating/editing sources.

**Comment by richard-cox** [comment]
I've created https://github.com/epinio/ui/issues/347 to cover test how 1.10 changes affect the UI
