### ISSUE TITLE
Refine and update the old README

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2428]
The README is a bit outdated. We should refine it.

Ideas:
- First section should be something like "what epinio is, and what problem does it solves", and the links to docs, sites and other references.
- remove the contents section (too long and not really needed)
- remove the old references (i.e.: linkerd)
- update configurations and services
- put some quickstart references (how to install from charts for a standalone installation, on [rancher](https://docs.epinio.io/howtos/install_epinio_on_rancher) and how to install the CLI). Eventually add links to the docs)
- some quick examples commands?
- Reach us section !important!
- Update License, keep contributing (OSS)
- Drop buildpacks reference
```[tasklist]
### Tasks
- [x] new first section (what is it, what problem is solved)
- [x] remove table of contents
- [x] remove old references (linkerd)
- [ ] update configuration and service information
- [x] add quickstart references
- [x] quick example commands
- [ ] highlight section `reach us`
- [ ] update license, contribution information
- [ ] drop buildpack refs
```

**Comment by andreas-kupries** [comment]
Notes:

- We already have a `what does it solve` section - https://github.com/epinio/epinio#what-problem-does-epinio-solve
- We already have a quick start reference - https://github.com/epinio/epinio#usage
- This contains the example commands as well
-
