### ISSUE TITLE
Add `--output json` flag to CLI

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2526]
** JSON output

Some commands could have a JSON output instead of the table rendering, usefulo for some automation.

Ref:
 - https://github.com/epinio/epinio/issues/435
 - https://github.com/epinio/epinio/issues/2525

```[tasklist]
### Tasks
- [ ] https://github.com/epinio/epinio/issues/2527
- [ ] https://github.com/epinio/epinio/issues/2558
- [ ] https://github.com/epinio/epinio/issues/2613
- [ ] https://github.com/epinio/epinio/issues/2614
```

**Comment by gitricko** [comment]
I think namespace is good. Another critical one for us are configurations because of the issue that we state previously. The nice thing is that we can get it back to work once we downgrade our CLI to 1.8.1 but server 1.9.0 which is not ideal but it works.

Why configuration is important is because there are times we want to read back our configuration via cli (not inside container) for CI/CD purpose and automation
