### ISSUE TITLE
Docker Desktop UI enhancements

### ISSUE THREAD

**Issue by jhmarina** [epinio/epinio#2621]
**Describe the Epic **

A clear and concise description of what is desired. In case of new features this has a strong
overlap with the first task below.

Hint: Make sure to search through the existing (possibly closed) issues, as they often contain
important information on recent changes.

**Additional context**

Add any other context about the epic here.

**Tasks**

- [ ] Specify a new feature, or investigate an undesired behaviour
- [ ] Implement the specification, or bug fix coming out of the investigation
- [ ] Write and/or update tests covering the new or changed behaviour to be run by CI
- [ ] For larger changes request QA to test/verify the changes as well, outside of CI.
- [ ] Update the documentation
        - [ ] Reference description (maybe just update CLI manpages)
        - [ ] Explanations for a new feature
        - [ ] How To Use a new feature
        - [ ] A tutorials
- [ ] Write and publish a blog post for
        - New features,
	- Important bug fixes, and
	- Breaks in backward compatibility
