### ISSUE TITLE
New Authorization Roles

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2631]
This Epic is to track the spike and the practical tasks regarding https://github.com/epinio/epinio/issues/1946

New incoming subsequent smaller tasks will be added to the tasklist.

**Tasks**

```[tasklist]
### Tasks
- [ ] https://github.com/epinio/epinio/pull/2677
- [ ] https://github.com/epinio/docs/pull/360
- [ ] https://github.com/epinio/epinio/issues/2632
- [ ] https://github.com/epinio/epinio/pull/2640
- [ ] https://github.com/epinio/epinio/pull/2648
- [ ] https://github.com/epinio/epinio/pull/2676
- [ ] https://github.com/epinio/epinio/pull/2656
```
