### ISSUE TITLE
Create Helm chart for Epinio

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#936]
We want to give users easy ways to deploy Epinio (as in "one click"). A helm chart in some public repo is one such way. 

Check https://github.com/manno/epinio-installer as an option to add Epinio to helm hubs.

So regarding the helm chart, yes a pipeline that publishes an up to date helm chart to a repo is needed. However we also have to take care of the repo. Since helm 3 there is no central Helm repo anymore.
Then we can register the Repo with different sites, like https://artifacthub.io/  or Rancher, thus gaining visibility.

This is what Quarks used for its repo: https://github.com/cloudfoundry-incubator/quarks-helm (index.yaml)
CI:
https://github.com/cloudfoundry-incubator/quarks-operator/blob/master/.github/workflows/quarks-operator-ci.yaml#L264-L339
I hope there are easier ways to do that now, like a Github Action

- [x]  Create a [chart repo](https://helm.sh/docs/topics/chart_repository/)
- [x] Automate the deployment with [GHA](https://helm.sh/docs/howto/chart_releaser_action/)
- [x] Build epinio-installer container when we release a new Epinio version
https://github.com/epinio/epinio/pull/945
- [x] Move my [repo](https://github.com/juadk/epinio-helm-chart) to the Epinio Organization
- [x] Automatically release new Helm Chart version when we release Epinio - https://github.com/epinio/epinio/pull/962
- [x] Register the repo with different sites like [artifact hub](https://artifacthub.io/) (just tested, pretty straightforward)
      We need an email account (https://github.com/epinio/epinio/issues/967)
The chart is referenced here https://artifacthub.io/packages/helm/epinio/epinio
I use my email waiting the official one.
- [x] Write documentation - https://github.com/epinio/epinio/issues/968
- [x] Fix the CI, use k3d to test the helm chart
https://github.com/epinio/epinio-helm-chart/runs/4154011078?check_suite_focus=true

**Comment by juadk** [comment]
Basics options are working but I don't know how to manage the case when we need to install ingress controller first, configure the DNS and install Epinio. 
Mainly because there is a manual step (the DNS setup) in the process.
I asked advises form Helm experts and one solution could be to have 2 charts with dependency:
- one chart for installing the ingress controller if we need one (epinio-ingress)
- another chart for deploying Epinio once the DNS is up-to-date.

I'm not sure we can use Helm like that, let's give it a try.

**Comment by juadk** [comment]
The official repo is live - https://github.com/epinio/epinio-helm-chart

**Comment by manno** [comment]
Three more things which should be a separate issue (?):

- air gap support via image arg (existing Rancher mechanism)
- image annotations for artifacthub.io security scanning (manually kept in sync)
- Rancher Helm question UI support
