### ISSUE TITLE
CI to test Epinio on Rancher Desktop 

### ISSUE THREAD

**Issue by prabalsharma** [epinio/epinio#940]
One option is to do a PoC to test Epinio on Rancher Desktop (Windows, then Linux, MacOS after?) with openQA through CI self-hosted runners.

```[tasklist]
### Tasks
- [X] https://github.com/epinio/epinio/issues/1682
- [ ] https://github.com/epinio/epinio/issues/1683
- [ ] https://github.com/epinio/epinio/issues/1684
```

**Comment by juadk** [comment]
Today, we discussed about it with @ldevulder .
It should be possible to use what Rancher desktop team has started but apparently they are thinking about moving from cirrus ci to github action. 
So we shouldn't try to do something with cirrus at all.
Maybe we can do a POC to test Playwright scripts in one of our selfhosted runner?
https://github.com/rancher-sandbox/rancher-desktop/tree/main/e2e
From what I can see, it doesn't look like too hard adding an Epinio test but who knows :-)

**Comment by prabalsharma** [comment]
Acceptance Criteria: 

- Nightly CI should test Epinio against latest release of Rancher Desktop.
- use rdctl to install RD 
- install epinio
- check if epinio endpoint can be reached
- push sample app
- check if sample app can be reached
